################################################################################
# Automatically-generated file. Do not edit!
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/hal_init_pre.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.c \
../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/system_stm32f4xx.c 

OBJS += \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/hal_init_pre.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.o \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/system_stm32f4xx.o 

C_DEPS += \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/hal_init_pre.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_adc_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_can.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cec.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cortex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_crc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_cryp_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dac_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dcmi_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dfsdm.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma2d.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dma_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_dsi.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_eth.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_flash_ramfunc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_fmpi2c_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_gpio.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hash_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_hcd.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2c_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_i2s_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_irda.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_iwdg.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_lptim.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_ltdc_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_mmc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nand.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_nor.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pccard.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pcd_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_pwr_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_qspi.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rcc_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rng.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_rtc_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sai_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sd.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sdram.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_smartcard.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spdifrx.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_spi.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_sram.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_tim_ex.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_uart.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_usart.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_hal_wwdg.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_adc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_crc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dac.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_dma2d.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_exti.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fmc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_fsmc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_gpio.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_i2c.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_lptim.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_pwr.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rcc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rng.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_rtc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_sdmmc.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_spi.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_tim.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usart.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_usb.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/stm32f4xx_ll_utils.d \
./mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/system_stm32f4xx.d 


# Each subdirectory must supply rules for building sources it contributes
mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/%.o: ../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device/%.c
	@echo 'Building file: $<'
	@echo 'Invoking: Cross ARM C Compiler'
	arm-none-eabi-gcc -mcpu=cortex-m4 -mthumb -mfloat-abi=softfp -mfpu=fpv4-sp-d16 -O0 -fmessage-length=0 -ffunction-sections -fdata-sections -fno-builtin -funsigned-char -fno-delete-null-pointer-checks -fomit-frame-pointer -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers  -g3 -DTARGET_STM32F429xx -DDEVICE_SPISLAVE=1 -D__MBED__=1 -D__FPU_PRESENT=1 -DTRANSACTION_QUEUE_SIZE_SPI=2 -DUSBHOST_OTHER -DDEVICE_PORTINOUT=1 -DTARGET_RTOS_M4_M7 -DDEVICE_RTC=1 -DTOOLCHAIN_object -DDEVICE_SERIAL_ASYNCH=1 -DTARGET_STM32F4 -D__CMSIS_RTOS -DTOOLCHAIN_GCC -DARM_MATH_CM4 -DTARGET_LIKE_CORTEX_M4 -DTARGET_M4 -DTARGET_UVISOR_UNSUPPORTED -DDEVICE_PORTOUT=1 -DMBED_BUILD_TIMESTAMP=1511263925.01 -DDEVICE_SPI_ASYNCH=1 -DDEVICE_INTERRUPTIN=1 -DTARGET_CORTEX -DTARGET_STM32F429 -DRTC_LSI=1 -D__CORTEX_M4 -DDEVICE_STDIO_MESSAGES=1 -DTARGET_FAMILY_STM32 -DTARGET_DISCO_F429ZI -DDEVICE_PORTIN=1 -DTARGET_RELEASE -DTARGET_STM -DDEVICE_SERIAL_FC=1 -DDEVICE_TRNG=1 -DTARGET_LIKE_MBED -DTARGET_STM32F429ZI -D__MBED_CMSIS_RTOS_CM -DDEVICE_SLEEP=1 -DTOOLCHAIN_GCC_ARM -DDEVICE_SPI=1 -DTARGET_STM32F429xI -DDEVICE_SERIAL=1 -DTARGET_CORTEX_M -DOVERRIDE=virtual -I../ -I../img -I../mbed-os/. -I../mbed-os/features -I../mbed-os/features/frameworks -I../mbed-os/features/frameworks/greentea-client -I../mbed-os/features/frameworks/greentea-client/greentea-client -I../mbed-os/features/frameworks/greentea-client/source -I../mbed-os/features/frameworks/unity -I../mbed-os/features/frameworks/unity/source -I../mbed-os/features/frameworks/unity/unity -I../mbed-os/features/frameworks/utest -I../mbed-os/features/frameworks/utest/source -I../mbed-os/features/frameworks/utest/utest -I../mbed-os/features/mbedtls -I../mbed-os/features/mbedtls/importer -I../mbed-os/features/mbedtls/inc -I../mbed-os/features/mbedtls/inc/mbedtls -I../mbed-os/features/mbedtls/src -I../mbed-os/features/mbedtls/platform -I../mbed-os/features/mbedtls/platform/inc -I../mbed-os/features/mbedtls/platform/src -I../mbed-os/features/mbedtls/targets -I../mbed-os/features/mbedtls/targets/TARGET_STM -I../mbed-os/features/mbedtls/targets/TARGET_STM/TARGET_STM32F4 -I../mbed-os/features/nanostack -I../mbed-os/features/storage -I../mbed-os/features/netsocket -I../mbed-os/features/netsocket/cellular -I../mbed-os/features/netsocket/cellular/generic_modem_driver -I../mbed-os/features/netsocket/cellular/utils -I../mbed-os/features/filesystem -I../mbed-os/features/filesystem/bd -I../mbed-os/features/filesystem/fat -I../mbed-os/features/filesystem/fat/ChaN -I../mbed-os/cmsis -I../mbed-os/cmsis/TARGET_CORTEX_M -I../mbed-os/cmsis/TARGET_CORTEX_M/TOOLCHAIN_GCC -I../mbed-os/cmsis/TOOLCHAIN_GCC -I../mbed-os/drivers -I../mbed-os/events -I../mbed-os/events/equeue -I../mbed-os/rtos -I../mbed-os/rtos/TARGET_CORTEX -I../mbed-os/rtos/TARGET_CORTEX/rtx4 -I../mbed-os/rtos/TARGET_CORTEX/rtx5 -I../mbed-os/rtos/TARGET_CORTEX/rtx5/TARGET_RTOS_M4_M7 -I../mbed-os/rtos/TARGET_CORTEX/rtx5/TARGET_RTOS_M4_M7/TOOLCHAIN_GCC -I../mbed-os/hal -I../mbed-os/hal/storage_abstraction -I../mbed-os/platform -I../mbed-os/targets -I../mbed-os/targets/TARGET_STM -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4 -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/TARGET_DISCO_F429ZI -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/TARGET_STM32F429xI/device/TOOLCHAIN_GCC_ARM -I../mbed-os/targets/TARGET_STM/TARGET_STM32F4/device -I../rapidjson/include -I../esp8266-driver -I../esp8266-driver/ESP8266 -I../Application -I../Application/online-apis -include../mbed_config.h -std=gnu99 -DMBED_DEBUG -DMBED_TRAP_ERRORS_ENABLED=1 -MMD -MP -MF"$(@:%.o=%.d)" -MT"$(@)" -c -o "$@" "$<"
	@echo 'Finished building: $<'
	@echo ' '


